name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Build/release Electron app
        inputs:
          skip_package_manager_install:
            description: Whether to skip package manager install
            required: false
            default: false
          package_manager:
            description: Package manager to use (`pnpm | yarn | npm`)
            required: false
            default: "npm"
          github_token:
            description: GitHub authentication token
            required: true
          mac_certs:
            description: Base64-encoded code signing certificate for macOS
            required: false
          mac_certs_password:
            description: Password for decrypting `mac_certs`
            required: false
          release:
            description: Whether the app should be released after a successful build
            required: false
            default: false
          windows_certs:
            description: Base64-encoded code signing certificate for Windows
            required: false
          windows_certs_password:
            description: Password for decrypting `windows_certs`
            required: false
          package_root:
            description: Directory where NPM/Yarn commands should be run
            required: false
            default: "."
          build_script_name:
            description: Name of the optional NPM build script which is executed before `electron-builder`
            required: false
            default: build
          skip_build:
            description: Whether the action should execute the NPM build script before running `electron-builder`
            required: false
            default: false
          use_vue_cli:
            description: Whether to run `electron-builder` using the Vue CLI plugin instead of calling the command directly
            required: false
            default: false
          args:
            description: Other arguments to pass to the `electron-builder` command, e.g. configuration overrides
            required: false
            default: ""
          max_attempts:
            description: Maximum number of attempts for completing the build and release step
            required: false
            default: "1"

          # Deprecated
          app_root:
            description: Directory where `electron-builder` commands should be run
            required: false

        runs:
          using: node20
          main: index.js

        branding:
          icon: cloud-lightning
          color: blue
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings) 
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
